credentials:
  usernames:
    admin:
      email: admin@gmail.com
      name: Administrateur
      password: abc123
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
    - admin@gmail.com
    