credentials:
  usernames:
    admin:
      email: "admin@gmail.com"
      name: "Administrateur"
      password: "abc123"
cookie:
  expiry_days: 30
  key: "signature_unique_123"
  name: "auth_cookie"
preauthorized:
  emails:
    - "admin@gmail.com"
